[project]
name = "streamlit-pasword-suggestion"
version = "0.1.0"
description = "Simple Python + Streamlit Password Strength Meter "
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.43.2",
]
